### ISSUE TITLE
fakegatoStorage Issue Tracker and backlog

### ISSUE THREAD

**Issue by NorthernMan54** [simont77/fakegato-history#25]
Backlog

* [x] Revisit logging, current too verbose even for debug
* [x] Google Drive - Add retries for 'User Rate Limit Exceeded' after a small interval for both fakegato-history.load and fakegato-history.save
* [x] fakegato-history - this.log.debug("**ERROR fetching persisting data restart from zero - invalid JSON**",e);
     cb(e,false);  // fakegato-history This needs testing
* [x] Added hostname to drive file name, so that test and prod data can
be separate. ( May need to rethink this further. )

Issues

* [x] Google Drive - on reboot my motion accessory issue two addentry one after the other, this creates two files, and then everything starts going crazy, if I remove the extra files then always seems ok
* [x] Google Drive - Fix creation of multiple folders when none exist

**Comment by NorthernMan54** [comment]
fakegato-history - this.log.debug("ERROR fetching persisting data restart from zero - invalid JSON",e);
cb(e,false);  // fakegato-history This needs testing

I tested this logic and it works.
